---

- name:       "Installing NSD using Ansible..."
  hosts:      all
  connection: local
  tasks:
    - name: install_packages
      apt:
        name:         "{{ item }}"
        update_cache: yes
      with_items:
        - "nsd"
      register: install_packages
