---

- name: "Installing NSD using Ansible..."
  hosts: all
  connection: local
  tasks:

    - name: create_users
      user:
        name: "{{ item }}"
      with_items:
        - "nsd"
      register: create_users

    - name: install_packages
      when: create_users|success
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - "nsd"
      register: install_packages

    - name: generate_nsd_config
      when: create_users|success
      command: "nsd-control-setup"
      register: generate_nsd_config

    - name: amend_nsd_config
      when: generate_nsd_config|success
      template:
        src:    nsd.conf.j2
        dest:   /etc/nsd/nsd.conf
        owner:  root
        group:  root
        mode:   "u=rw,g=r,o=r"
      register: amend_nsd_config
